worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include       C:/Users/HP/Desktop/nginx-1.30.2/conf/mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;
 
  server {
    listen       8080 default_server;
    server_name  localhost 127.0.0.1 _;

    root C:/Users/HP/Desktop/stock-app/stock-app/dist/public/browser;
    index index.html index.htm;

    location /api/ {
      proxy_pass http://127.0.0.1:3000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
